config/routes.rb
Rails.application.routes.draw do
  root to: 'stories#index'
  
  devise_for :users
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  extend SimpleEnum::Attribute

  attr_accessor :dirty_country

  after_save :create_country
  validates :title, :body, :user_id, :country, :state, :city, :weather_season, :type_of_experience, presence: true

  belongs_to :user

  as_enum :weather_season, %i{Summer Spring Winter Autumn}, pluralize_scopes: false
  as_enum :type_of_experience, %i{Work Holidays General}, pluralize_scopes: false



  def dirty_country
    return ISO3166::Country.new(country) if @dirty_country.nil?
    @dirty_country
  end

  private

  def create_country
    @dirty_country = ISO3166::Country.new(country)
  end

    
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_many :stories, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @stories = Story.all
  end
  
  def create
    story = Story.create(strong_params.merge(user_id: current_user.id))
    
    if story.save
      flash[:success] = "Story created successfully"
      redirect_to root_path
    else
      @story = story
      render :new
    end
  end

  def new
    @story = Story.new
  end


  def strong_params
    params.require(:story).permit(:country, :state, :city, :weather_season, :title, :body, :user_id, :type_of_experience)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/stories_controller_helper.rb
module StoriesControllerHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/home/country_state_select.js.erb
<%# function CountryStateSelect(options) {
  var state_id = options['state_id'];
  var country_id = options['country_id'];
  var city_id = options['city_id'];

  var state_name = $('#' + state_id).attr('name');
  var state_class = $('#' + state_id).attr('class');

  var city_name = $('#' + city_id).attr('name');
  var city_class = $('#' + city_id).attr('class');

  return statesDropdown();
}
function statesDropdown() {

  addChosenToCountry();
  addChosenToState();
  addChosenToCity();

  $("#" + country_id).change(function () {
    return findStates($(this).val());
  });

}

function citiesDropdown() {
    $("#" + state_id).change(function () {
    return findCities($("#" + state_id).val(),$("#" + country_id).val());
  });
}

function addChosenToState(){
  if (chosenIsRequired() && stateIsNotText()) {
    $('#' + state_id).chosen(options['chosen_options']);
  }
}

function addChosenToCity(){
  if (chosenIsRequired() && cityIsNotText()) {
    $('#' + city_id).chosen(options['chosen_options']);
  }
}

function stateIsNotText(){
  return !$('#' + state_id).is("[type=text]");
}

function cityIsNotText(){
  return !$('#' + city_id).is("[type=text]");
}

function addChosenToCountry(){
  if (chosenIsRequired()) {
    $('#' + country_id).chosen(options['chosen_options']);
  }
}

function removeChosenFromFields(){
  if (chosenIsRequired()) {
    $("#" + options['state_id'] + "_chosen").remove();
    $("#" + options['city_id'] + "_chosen").remove();
  }
}

function removeChosenFromCityFields(){
  if (chosenIsRequired()) {
    $("#" + options['city_id'] + "_chosen").remove();
  }
}

function chosenIsRequired(){
  return options.hasOwnProperty("chosen_ui") && options['chosen_ui'];
}

function findStates(id) {

  //Remove all Chosen from existing fields
  removeChosenFromFields();
  findCities('','')

  //Perform AJAX request to get the data; on success, build the dropdown
  $.ajax({
    url: "/find_states",
    type: 'post',
    dataType: 'json',
    cache: false,
    data: {country_id: id},
    success: function (data) { buildStatesDropdown(data) }
  });
}

function findCities(state_id, country_id) {

  //Remove all Chosen from existing fields
  removeChosenFromCityFields();

  //Perform AJAX request to get the data; on success, build the dropdown
  $.ajax({
    url: "/find_cities",
    type: 'post',

    dataType: 'json',
    cache: false,
    data: {
      country_id: country_id,
      state_id: state_id
    },
    success: function (data) { buildCitiesDropdown(data) }
  });
}

//Build the HTML for our dropdown menus
function buildStatesDropdown(data) {

  if (data.length === 0) {
    html = '<input id="' + state_id + '" name="' + state_name + '" class="' + state_class + '" type="text"  type="text" value="" >';
  } else {
    html = '<select id="' + state_id + '" name="' + state_name + '" class="' + state_class + '" >';
    html += '<option>'+ find_select_option_text('state') +'</option>'

    for (i = 0; i < data.length; i++) {
      html += '<option value='+data[i][0]+'>' + data[i][1] + '</option>';
    }

    html += '</select>';
  }


  $('#' + state_id).replaceWith(html);

  //This has to happen AFTER we've replaced the dropdown or text
  if (data.length > 0) {
    addChosenToState();
  }

  // [142] FIXME # Is there any other way to call city method , it is adding change method in every state change 
  if(typeof city_name !== "undefined" ){
    citiesDropdown();
  };

}

function find_select_option_text(type){
    if (type === 'city'){
      return options['city_place_holder'];
    }else{
      return options['state_place_holder']
    }

}

function buildCitiesDropdown(data) {

  if (data.length === 0) {
    html = '<input id="' + city_id + '" name="' + city_name + '" class="' + city_class + '" type="text"  type="text" value="" >';
  } else {
    html = '<select id="' + city_id + '" name="' + city_name + '" class="' + city_class + '" >';
    html += '<option>'+ find_select_option_text('city') +'</option>'
    for (i = 0; i < data.length; i++) {
      html += '<option>' + data[i] + '</option>';
    }

    html += '</select>';
  }

  $('#' + city_id).replaceWith(html);

  //This has to happen AFTER we've replaced the dropdown or text
  if (data.length > 0) {
    addChosenToCity();
  }
}
} %>

app/views/home/index.html.haml
.container
  .panel
    .panel-heading
      %h1 Add Story
  .panel-body
    = render partial: "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tellus
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    -# = tag :meta, name: :psj, action: action_name, controller: controller_name
    
  %body{class:"#{controller_name} #{action_name}"}
    - flash.each do |key, value|
      %div{class: "text-center alert alert-#{key}"}
        = link_to '#', class: 'close', data: {dismiss: "alert"} do
          ×
        = value
    = yield

app/views/stories/_form.html.haml
= simple_form_for(@story, wrapper_mappings:{    radio_buttons:  :vertical_collection}) do |f|
  = f.error_notification
  = f.input :title, input_html: { placeholder: 'Give a cool title to your story' }
  = f.input :country, label: 'Country', collection: CountryStateSelect.countries_collection
  = f.input :state, CountryStateSelect.state_options(label: 'State / Province', form: f, field_names: { :country => :country, :state => :home_state } )
  = f.input :city, CountryStateSelect.city_options(label: 'City', form: f, field_names: {  :state => :state, :city => :home_city } )
  = f.input :weather_season,  as: :radio_buttons, collection: Story.weather_seasons.keys, required: true
  = f.input :type_of_experience, as: :radio_buttons, collection: Story.type_of_experiences.keys, required: true

  %br/
  = f.input :body, as: :text, label: 'Story', rows: 5
  %br/
  = f.button :submit, class: 'btn btn-primary'

  = link_to 'Cancel', stories_path, class: 'btn btn-danger'
  
    

app/views/stories/index.html.haml
%h1 Listing Stories
%table.table
  %thead.black.white-text
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Country
      %th{:scope => "col"} City
      %th{:scope => "col"} Season
  %tbody
    - @stories.each do |story|
      %tr
        %th{:scope => "row"} 
          = story.id
        %td
          = story.dirty_country.name
        %td
          = story.city
        %td
          = story.weather_season

= link_to 'New Story', new_story_path, class: "btn btn-success", id:'new-story', data: { no_turbolink: true }
%br
= link_to 'Log out', destroy_user_session_path, method: 'DELETE' if user_signed_in?

app/views/stories/new.html.haml
.container.story.new
  .panel
    .panel-heading
      %h1 Add Story
  .panel-body
    = render partial: "form"